### ISSUE TITLE
提示这种错误

### ISSUE THREAD

**Issue by Shiuwn** [Why8n/EasyTrain#13]
[32m正在登录...[39m
Traceback (most recent call last):
  File ".\easytrain.py", line 48, in <module>
    main()
  File ".\easytrain.py", line 16, in main
    result, msg = login.login(USER_NAME, USER_PWD)
  File "F:\EasyTrain\train\login\Login.py", line 64, in login
    result, msg = self._login(userName, userPwd, type=(count % 2))
  File "F:\EasyTrain\train\login\Login.py", line 17, in wrapper
    reslut, msg = func(*args, **kw)
  File "F:\EasyTrain\train\login\Login.py", line 75, in _login
    return self._loginNormal(userName, userPwd)
  File "F:\EasyTrain\train\login\Login.py", line 79, in _loginNormal
    self._uamtk()
  File "F:\EasyTrain\train\login\Login.py", line 47, in _uamtk
    return isSuccess(jsonRet), \
  File "F:\EasyTrain\train\login\Login.py", line 45, in isSuccess
    return response['result_code'] == 0 if 'result_code' in response else False
TypeError: argument of type 'NoneType' is not iterable

**Comment by zc1342303** [comment]
同问题
