### ISSUE TITLE
图形验证码过程报错

### ISSUE THREAD

**Issue by Fheping** [Why8n/EasyTrain#15]
正在获取验证码..
 
            -----------------
            | 0 | 1 | 2 | 3 |
            -----------------
            | 4 | 5 | 6 | 7 |
            ----------------- 
输入验证码索引(见上图，以','分割）: 2,7
captchaResult: 180,40,250,110
captchaCheck: {'result_message': '验证码校验成功', 'result_code': '4'}
核验方式不正确！
核验方式不正确！
正在获取验证码..
Traceback (most recent call last):
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/easytrain.py", line 48, in <module>
    main()
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/easytrain.py", line 16, in main
    result, msg = login.login(USER_NAME, USER_PWD)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/train/login/Login.py", line 64, in login
    result, msg = self._login(userName, userPwd, type=(count % 2))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/train/login/Login.py", line 17, in wrapper
    reslut, msg = func(*args, **kw)
                  ^^^^^^^^^^^^^^^^^
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/train/login/Login.py", line 73, in _login
    return self._loginAsyncSuggest(userName, userPwd)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/train/login/Login.py", line 106, in _loginAsyncSuggest
    results, verify = Captcha().verifyCaptchaByHand(type=TYPE_LOGIN_OTHER_WAY)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fengheping/Desktop/mySpace/work/pros/EasyTrain/train/login/Capthca.py", line 69, in verifyCaptchaByHand
    img = Image.open(BytesIO(self.getCaptcha(type)))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x10d76bfb0>

**Comment by Fheping** [comment]
能看下这种是哪儿的问题么  图形码入参正确 请求ok  后续callback的时候抛出的

**Comment by Fheping** [comment]
核验方式不正确！ 是12306不让这么验证么

**Comment by fansea0** [comment]
我也是这种情况，请问你解决了吗

**Comment by VV1314** [comment]
+1

**Comment by huangzz1226** [comment]
我也是这种情况，有人解决了吗

**Comment by chujiawei123** [comment]
我也是这种情况

**Comment by igotyback** [comment]
我的错误
![image](https://github.com/Why8n/EasyTrain/assets/150988487/d6a9fc66-89fa-4fbe-977f-e023f1980ac3)

**Comment by igotyback** [comment]
也不报错

**Comment by Kiritoyh42** [comment]
核验方式不正确

**Comment by igotyback** [comment]
核验方式不正确怎末解决呢？
